server:
  port: 8881

management:
  endpoints:
    web:
      exposure:
        include: refresh

parameter-store:
  value: Some value

#cloud:
#  aws:
#    region:
#      auto: false
#      static: "eu-west-1"
#    stack.auto: false
#    credentials:
#      accessKey: ${AWS_ACCESS_KEY_ID:foobar}
#      secretKey: ${AWS_SECRET_ACCESS_KEY:foobar}